apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "platform"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "promotion"
            - name: "monaco"
            - name: "infrastructure-delivery"
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "smoke-test"
            - name: "release"
            - name: "evaluation"
              properties:
                timeframe: "15m"             

    - name: "staging" 
      sequences:
        - name: "artifact-delivery"
          triggeredOn:
            - event: "dev.artifact-delivery.finished"
          tasks:
            - name: "promotion"
            - name: "monaco"
            - name: "infrastructure-delivery"
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "smoke-test"
            - name: "test"

    - name: "production"
      sequences:
        - name: "artifact-delivery"
          triggeredOn:
            - event: "staging.artifact-delivery.finished"
          tasks:
            - name: approval
              properties: 
                pass: manual
                warning: manual
            - name: "promotion"
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
