metadata:
  initbranch: dev
services:
- name: left-leg
  triggerevent: sh.keptn.event.dev.artifact-delivery.triggered
- name: right-leg
  triggerevent: sh.keptn.event.dev.artifact-delivery.triggered
- name: right-arm
  triggerevent: sh.keptn.event.dev.artifact-delivery.triggered
- name: left-arm
  triggerevent: sh.keptn.event.dev.artifact-delivery.triggered
