affinity: {}
autoscaling:
    enabled: true
    maxReplicas: 6
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
bluegreen:
    enabled: true
fullnameOverride: ""
hats:
    repositoryBasename: podtato-hats
    servicePort: 8080
    serviceType: ClusterIP
    tag: 'distroless-v3-latest-dev'
images:
    pullPolicy: IfNotPresent
    pullSecrets: []
    repositoryDirname: ghcr.io/podtato-head
ingress:
    annotations: {}
    enabled: false
    hosts:
        - host: chart-example.local
          paths: []
    tls: []
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 2
resources: {}
securityContext: {}
serviceAccount:
    annotations: {}
    create: true
    name: ""
stage: dev
tolerations: []
