apiVersion: v2
actions:
  - name: "infrastructure"
    events:
      - name: "sh.keptn.event.infrastructure-delivery.triggered"
    tasks:
      - name: "crossplane"
        maxPollDuration: 1200
        files:
          - scripts
        image: "ghcr.io/thschue/kubectl:latest"
        imagePullPolicy: "Always"
        cmd:
          - "ash"
        args:
          - "/keptn/scripts/run_crossplane.sh"

  - name: "k6-smoke"
    events:
      - name: "sh.keptn.event.smoke-test.triggered"
    tasks:
      - name: "k6"
        files:
          - k6
        image: "loadimpact/k6"
        cmd:
          - sh
        args:
          - /keptn/k6/run-smoke-test.sh

  - name: "release"
    events:
      - name: "sh.keptn.event.release.triggered"
    tasks:
      - name: "argo-promote"
        image: "quay.io/argoproj/kubectl-argo-rollouts:master"
        args: ["promote","podtato-right-leg","-n","podtatohead-dev"]

  - name: "get-infra-version"
    events:
      - name: "sh.keptn.event.infra-version.triggered"
    tasks:
      - name: "getVersion"
        files:
          - scripts
        image: "ghcr.io/thschue/kubectl:latest"
        imagePullPolicy: "Always"
        cmd:
          - "ash"
        args:
          - "/keptn/scripts/check_infra_version.sh"
        env:
          - name: INFRAVERSION
            value: "$.data.labels.version"
            valueFrom: event
