stage: staging

# applies to all deployments in this chart
replicaCount: 2
images:
  repositoryDirname: ghcr.io/podtato-head
  pullPolicy: IfNotPresent
  pullSecrets: []

leftLeg:
  tag: "{{ keptn/ImageVersion }}"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
